/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.util.ArrayList;

/**
 *
 * @author Vero
 */
public class Marcador extends javax.swing.JFrame {

    ArrayList marcadores = new ArrayList();
    ArrayList valores = new ArrayList();
    int contadorPlayer1 = 0;
    int contadorPlayer2 = 0;

    /**
     * Creates new form Marcador
     */
    public Marcador() {
        initComponents();

        marcadores.add(0, "15");
        marcadores.add(1, "30");
        marcadores.add(2, "40");
        marcadores.add(3, "A");
        marcadores.add(4, " ");
        nuevoJuego.setEnabled(false);

    }

    public boolean gana1() {

        boolean resultado = false;
        if (contadorPlayer1 - 2 == contadorPlayer2) {
            if (contadorPlayer1 == 3) {
                resultado = true;
                marcadorJugador2.setText("");
            }
        } else {
            resultado = false;
        }
        return resultado;

    }

    public boolean gana2() {

        boolean resultado = false;
        if (contadorPlayer2 - 2 == contadorPlayer2) {
            if (contadorPlayer2 == 3) {
                resultado = true;
                marcadorJugador2.setText("");
            }
        } else {
            resultado = false;
        }
        return resultado;

    }

    public boolean ganaPlayer1() {
        boolean resultado = false;
        if (marcadorJugador1.getText().equals(" ")) {
            if (marcadorJugador2.getText().equals("40")) {
                resultado = true;
                marcadorJugador2.setText("");
            }
        } else {
            resultado = false;
        }
        return resultado;
    }

    public boolean ganaPlayer2() {
        boolean resultado = false;
        if (marcadorJugador2.getText().equals(" ")) {
            if (marcadorJugador1.getText().equals("40")) {
                resultado = true;
                marcadorJugador1.setText("");
            }
        } else {
            resultado = false;
        }

        return resultado;

    }

    public boolean deuce() {
        boolean resultado = false;
        if (marcadorJugador1.getText().equals("40")) {
            if (marcadorJugador2.getText().equals("40")) {
                resultado = true;
            }
        } else {
            resultado = false;
        }

        return resultado;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        puntoJugador1 = new javax.swing.JToggleButton();
        marcadorJugador1 = new javax.swing.JLabel();
        winner1 = new javax.swing.JLabel();
        puntoJugador2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        marcadorJugador2 = new javax.swing.JLabel();
        winner2 = new javax.swing.JLabel();
        nuevoJuego = new javax.swing.JToggleButton();
        deuce = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Player 1");

        puntoJugador1.setText("Punto");
        puntoJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoJugador1ActionPerformed(evt);
            }
        });

        puntoJugador2.setText("Punto");
        puntoJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoJugador2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Player 2");

        nuevoJuego.setText("Nuevo Juego");
        nuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(winner1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puntoJugador2)
                            .addComponent(jLabel2)
                            .addComponent(marcadorJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(winner2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puntoJugador1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(marcadorJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deuce, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(nuevoJuego)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(nuevoJuego)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(marcadorJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(puntoJugador1)
                                    .addComponent(puntoJugador2)))
                            .addComponent(marcadorJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(winner2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deuce, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(winner1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puntoJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoJugador1ActionPerformed
        marcadorJugador1.setText(marcadores.get(contadorPlayer1).toString());

        if (ganaPlayer1() == true) {
            winner1.setText("¡¡WINNER!!");
            winner2.setText("¡¡LOSER!!");
            marcadorJugador2.setText(" ");
            puntoJugador1.setEnabled(false);
            puntoJugador2.setEnabled(false);
            nuevoJuego.setEnabled(true);
        }

        if (deuce() == true) {
            deuce.setText("DEUCE");
        } else {
            deuce.setText("");

        }

        if (gana1() == true) {
            winner1.setText("¡¡WINNER!!");
            winner2.setText("¡¡LOSER!!");
            marcadorJugador2.setText(" ");
            puntoJugador1.setEnabled(false);
            puntoJugador2.setEnabled(false);
            nuevoJuego.setEnabled(true);
        }

        contadorPlayer1++;
    }//GEN-LAST:event_puntoJugador1ActionPerformed

    private void puntoJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoJugador2ActionPerformed

        marcadorJugador2.setText(marcadores.get(contadorPlayer2).toString());

        if (ganaPlayer2() == true) {
            winner2.setText("¡¡WINNER!!");
            winner1.setText("¡¡LOSER!!");
            puntoJugador2.setEnabled(false);
            puntoJugador1.setEnabled(false);
            nuevoJuego.setEnabled(true);

        }

        if (deuce() == true) {
            deuce.setText("DEUCE");
        } else {
            deuce.setText("");

        }

        if (gana2() == true) {
            winner2.setText("¡¡WINNER!!");
            winner1.setText("¡¡LOSER!!");
            marcadorJugador2.setText(" ");
            puntoJugador1.setEnabled(false);
            puntoJugador2.setEnabled(false);
            nuevoJuego.setEnabled(true);
        }

        contadorPlayer2++;
    }//GEN-LAST:event_puntoJugador2ActionPerformed

    private void nuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJuegoActionPerformed
        // TODO add your handling code here:

        winner1.setText("");
        winner2.setText("");
        marcadorJugador1.setText("");
        marcadorJugador2.setText("");
        puntoJugador1.setEnabled(true);
        puntoJugador2.setEnabled(true);
        nuevoJuego.setEnabled(false);
        contadorPlayer1 = 0;
        contadorPlayer2 = 0;
    }//GEN-LAST:event_nuevoJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marcador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deuce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel marcadorJugador1;
    private javax.swing.JLabel marcadorJugador2;
    private javax.swing.JToggleButton nuevoJuego;
    private javax.swing.JToggleButton puntoJugador1;
    private javax.swing.JToggleButton puntoJugador2;
    private javax.swing.JLabel winner1;
    private javax.swing.JLabel winner2;
    // End of variables declaration//GEN-END:variables
}
